### ISSUE TITLE
Octokit.NotFoundException: repositories/X/contents/icons/obj?ref=Y

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/IconDiffBot#32]
https://github.com/tgstation/tgstation/pull/38270/checks

```
Octokit.NotFoundException: repositories/3234987/contents/icons/obj?ref=425318e88965531fba06d71b6b4a50cad66aaded was not found.
   at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext() in D:\octokit.net\Octokit\Clients\ApiPagination.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IconDiffBot.Core.GitHubManager.<GetFileAtCommit>d__10.MoveNext() in /src/IconDiffBot/GitHubManager.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IconDiffBot.Core.PayloadProcessor.<>c__DisplayClass10_2.<<GenerateDiffs>g__GetImageFor|4>d.MoveNext() in /src/IconDiffBot/PayloadProcessor.cs:line 215
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IconDiffBot.Core.PayloadProcessor.<>c__DisplayClass10_1.<<GenerateDiffs>g__DiffDmi|0>d.MoveNext() in /src/IconDiffBot/PayloadProcessor.cs:line 229
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IconDiffBot.Core.PayloadProcessor.<GenerateDiffs>d__10.MoveNext() in /src/IconDiffBot/PayloadProcessor.cs:line 285
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IconDiffBot.Core.PayloadProcessor.<ScanPullRequestImpl>d__9.MoveNext() in /src/IconDiffBot/PayloadProcessor.cs:line 153

```

**Comment by Cyberboss** [comment]
Spurious github failure it seems

**Comment by SpaceManiac** [comment]
Another one https://github.com/tgstation/tgstation/pull/38539/checks?check_run_id=4102785
