### ISSUE TITLE
Only 65535 characters are allowed; 186882 were supplied.

### ISSUE THREAD

**Issue by DamianX** [tgstation/IconDiffBot#43]
Only 65535 characters are allowed; 186882 were supplied.

```
Octokit.ApiValidationException: Invalid request.

Only 65535 characters are allowed; 186882 were supplied.
   at Octokit.Connection.HandleErrors(IResponse response) in D:\octokit.net\Octokit\Http\Connection.cs:line 665
   at Octokit.Connection.<RunRequest>d__58.MoveNext() in D:\octokit.net\Octokit\Http\Connection.cs:line 642
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__57`1.MoveNext() in D:\octokit.net\Octokit\Http\Connection.cs:line 626
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Patch>d__32`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IconDiffBot.Core.GitHubManager.<UpdateCheckRun>d__8.MoveNext() in /src/IconDiffBot/GitHubManager.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IconDiffBot.Core.PayloadProcessor.<HandleResults>d__13.MoveNext() in /src/IconDiffBot/PayloadProcessor.cs:line 437
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IconDiffBot.Core.PayloadProcessor.<GenerateDiffs>d__12.MoveNext() in /src/IconDiffBot/PayloadProcessor.cs:line 342
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IconDiffBot.Core.PayloadProcessor.<>c__DisplayClass11_0.<<ScanPullRequestImpl>g__RunCheck|0>d.MoveNext() in /src/IconDiffBot/PayloadProcessor.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IconDiffBot.Core.PayloadProcessor.<ScanPullRequestImpl>d__11.MoveNext() in /src/IconDiffBot/PayloadProcessor.cs:line 170
{"message":"Invalid request.\n\nOnly 65535 characters are allowed; 186882 were supplied.","documentation_url":"https://developer.github.com/v3/checks/runs/#update-a-check-run"}
```

a) commit: https://github.com/vgstation-coders/vgstation13/pull/18752/commits/46b38160949f7182d603d22de2e83b824956f1e4

b) check run: https://github.com/vgstation-coders/vgstation13/pull/18752/checks?check_run_id=7276200

**Comment by Cyberboss** [comment]
Ew github, you gay

**Comment by Cyberboss** [comment]
Ok so the only solution I can see to this is bisecting the results into different check runs
