### ISSUE TITLE
Error generating diffs

### ISSUE THREAD

**Issue by optimumtact** [tgstation/IconDiffBot#53]
```
Octokit.AuthorizationException: Bad credentials
   at Octokit.Connection.HandleErrors(IResponse response) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 665
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 642
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 626
   at Octokit.ApiConnection.Patch[T](Uri uri, Object data, String accepts)
   at IconDiffBot.Core.GitHubManager.UpdateCheckRun(Int64 repositoryId, Int64 installationId, Int64 checkRunId, CheckRunUpdate checkRunUpdate, CancellationToken cancellationToken) in /src/IconDiffBot/GitHubManager.cs:line 116
   at IconDiffBot.Core.PayloadProcessor.GenerateDiffs(PullRequest pullRequest, Int64 installationId, Int64 checkRunId, IReadOnlyList`1 changedDmis, IServiceScope scope, CancellationToken cancellationToken) in /src/IconDiffBot/PayloadProcessor.cs:line 337
   at IconDiffBot.Core.PayloadProcessor.<>c__DisplayClass11_0.<<ScanPullRequestImpl>g__RunCheck|0>d.MoveNext() in /src/IconDiffBot/PayloadProcessor.cs:line 156
--- End of stack trace from previous location where exception was thrown ---
   at IconDiffBot.Core.PayloadProcessor.ScanPullRequestImpl(Int64 repositoryId, Int32 pullRequestNumber, Int64 installationId, IServiceScope scope, CancellationToken cancellationToken) in /src/IconDiffBot/PayloadProcessor.cs:line 166
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```

**Comment by optimumtact** [comment]
Hi mum im on tv, also this error appearedd to be transient

**Comment by Cyberboss** [comment]
wew

**Comment by Poojawa** [comment]
```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> MySql.Data.MySqlClient.MySqlException: The table 'IconDiffs' is full ---> MySql.Data.MySqlClient.MySqlException: The table 'IconDiffs' is full
   at MySqlConnector.Core.ServerSession.TryAsyncContinuation(Task`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 1248
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 42
   --- End of inner exception stack trace ---
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 80
   at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 302
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 287
   at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at IconDiffBot.Core.PayloadProcessor.HandleResults(PullRequest pullRequest, Int64 installationId, Int64 checkRunId, List`1 diffResults, IServiceScope scope, IDatabaseContext databaseContext, CancellationToken cancellationToken) in /src/IconDiffBot/PayloadProcessor.cs:line 426
   at IconDiffBot.Core.PayloadProcessor.GenerateDiffs(PullRequest pullRequest, Int64 installationId, Int64 checkRunId, IReadOnlyList`1 changedDmis, IServiceScope scope, CancellationToken cancellationToken) in /src/IconDiffBot/PayloadProcessor.cs:line 338
   at IconDiffBot.Core.PayloadProcessor.<>c__DisplayClass11_0.<<ScanPullRequestImpl>g__RunCheck|0>d.MoveNext() in /src/IconDiffBot/PayloadProcessor.cs:line 156
--- End of stack trace from previous location where exception was thrown ---
   at IconDiffBot.Core.PayloadProcessor.ScanPullRequestImpl(Int64 repositoryId, Int32 pullRequestNumber, Int64 installationId, IServiceScope scope, CancellationToken cancellationToken) in /src/IconDiffBot/PayloadProcessor.cs:line 166
```

still an issue

**Comment by AffectedArc07** [comment]
@Poojawa that has since been resolved, and IDB can generate images again

**Comment by AffectedArc07** [comment]
@Cyberboss I think this can be closed as it relates to bad github credentials, which were fixed a long time ago, though I will leave it to you
