### ISSUE TITLE
Octokit.AuthorizationException: Bad credentials

### ISSUE THREAD

**Issue by ZeWaka** [tgstation/IconDiffBot#64]
This keeps happening a lot on goon for the past month or so. Happens for MapdiffBot as well.

Error:
```
Octokit.AuthorizationException: Bad credentials
   at Octokit.Connection.HandleErrors(IResponse response) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 665
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 643
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in C:\projects\octokit-net\Octokit\Http\Connection.cs:line 628
   at Octokit.ApiConnection.Get[T](Uri uri, IDictionary`2 parameters) in C:\projects\octokit-net\Octokit\Http\ApiConnection.cs:line 72
   at IconDiffBot.Core.GitHubManager.GetFileAtCommit(Int64 repositoryId, Int64 installationId, String filePath, String commit, CancellationToken cancellationToken) in /hosting/services/idb-building/IconDiffBot/Core/GitHubManager.cs:line 150
   at IconDiffBot.Core.PayloadProcessor.<>c__DisplayClass12_1.<<GenerateDiffs>g__GetImageFor|2>d.MoveNext() in /hosting/services/idb-building/IconDiffBot/Core/PayloadProcessor.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
   at IconDiffBot.Core.PayloadProcessor.<>c__DisplayClass12_0.<<GenerateDiffs>g__DiffDmi|0>d.MoveNext() in /hosting/services/idb-building/IconDiffBot/Core/PayloadProcessor.cs:line 259
--- End of stack trace from previous location where exception was thrown ---
   at IconDiffBot.Core.PayloadProcessor.GenerateDiffs(PullRequest pullRequest, Int64 installationId, Int64 checkRunId, IReadOnlyList`1 changedDmis, IServiceScope scope, CancellationToken cancellationToken) in /hosting/services/idb-building/IconDiffBot/Core/PayloadProcessor.cs:line 315
   at IconDiffBot.Core.PayloadProcessor.<>c__DisplayClass11_0.<<ScanPullRequestImpl>g__RunCheck|0>d.MoveNext() in /hosting/services/idb-building/IconDiffBot/Core/PayloadProcessor.cs:line 157
--- End of stack trace from previous location where exception was thrown ---
   at IconDiffBot.Core.PayloadProcessor.ScanPullRequestImpl(Int64 repositoryId, Int32 pullRequestNumber, Int64 installationId, IServiceScope scope, CancellationToken cancellationToken) in /hosting/services/idb-building/IconDiffBot/Core/PayloadProcessor.cs:line 166
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```

Failed check run:
https://github.com/goonstation/goonstation/pull/1594/checks?check_run_id=906278442
Similar but shorter stack trace here:
https://github.com/goonstation/goonstation/pull/1583/checks?check_run_id=902526522

**Comment by AffectedArc07** [comment]
I am well aware of this issue and it has been plaguing me for a while. Fix is unknown, so ill have to see if updating libs works. The fact this is spurious is hurting me.

**Comment by Cyberboss** [comment]
Ohhhhh I think I may know the issue

https://github.com/tgstation/IconDiffBot/blob/master/IconDiffBot/Core/GitHubManager.cs#L66

This `10` should be `-1` I was trying to adjust for clock skew and fucked up horribly.

**Comment by AffectedArc07** [comment]
Still occurs
https://github.com/ParadiseSS13/Paradise/pull/13822/checks?check_run_id=909465845

**Comment by Maldaris** [comment]
Hopefully more logs helps this.
https://github.com/WaspStation/WaspStation-1.0/pull/490/checks?check_run_id=1185854984

**Comment by ZeWaka** [comment]
Hasn't occurred in a long time for us.
